### ISSUE TITLE
ConnectionResetError: conection reset by peer.

### ISSUE THREAD

**Issue by xc-chengdu** [hukaixuan19970627/OrientedRepPoints_DOTA#1]
When I used a GPU for training, this error occurred before the end of an epoch, and the same error occurred after retrying several times. Have you encountered it before? How to solve it? Looking forward to your reply.

**Comment by hukaixuan19970627** [comment]
I haven't met this error before. Is there any problem with [GetStart.md](https://github.com/hukaixuan19970627/OrientedRepPoints_DOTA/blob/main/docs/GetStart.md)?

**Comment by hukaixuan19970627** [comment]
Some errors may have occurred while downloading the pretrained-backbone, try to set ''pretrained=None''.
