### ISSUE TITLE
请问一个关于正样本分配的问题。

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/OrientedRepPoints_DOTA#3]
非常好的设计。关于APAA 样本分配的部分，没有看懂。请问您是如何计算样本质量的呢？又是如何计算dynamic-k的值的呢？和OTA的有何区别呢？

谢谢

**Comment by hukaixuan19970627** [comment]
这个应该讲得比较清楚，其实和cascade里面的重采样思路是基本一致的，评价指标不一样而已
https://github.com/LiWentomng/OrientedRepPoints/issues/8
